[package]
name = "example"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1", features = [ "full" ] }
anyhow = "1"
sea-orm = { git = "https://github.com/SeaQL/sea-orm", features = [ "sqlx-sqlite", "runtime-tokio-rustls", "macros" ], default-features = false }
